name: smartbanking-dev

services:
  postgres:
    image: docker.io/library/postgres:16-alpine
    container_name: smartbanking-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    env_file: ./configs/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smartbanking"]
      interval: 5s
      timeout: 3s
      retries: 10
  
  redis:
    image: docker.io/library/redis:7-alpine
    container_name: smartbanking-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    env_file: ./configs/.env
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - ./data/redis:/data

  backend:
    build: ./backend
    image: smartbanking-backend:dev
    container_name: smartbanking-backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    env_file: ./configs/.env

  
networks:
  default:
    name: smartbanking-dev-net
